nodeLinker: pnp

npmScopes:
  thm:
    npmPublishRegistry: "https://thm.jfrog.io/thm/api/npm/thm-npm-prod/"
    npmRegistryServer: "https://thm.jfrog.io/thm/api/npm/thm-npm-prod/"

# packageExtensions:
#   "@firebase/firestore@*":
#     dependencies:
#       protobufjs: ^6.8.6
#   "@thm/fe-common-editor@*":
#     dependencies:
#       katex: ^0.10.0-rc.1

plugins:
    spec: "@yarnpkg/plugin-interactive-tools"

# yarnPath: .yarn/releases/yarn-3.1.1.cjs
